RedHatQE/cloudwash

README.md
cloudwash/cli.py
cloudwash/providers/azure.py
cloudwash/utils.py

delete whole resource group with `--all`  if all resources are older than SLA. deleting individual resources would be difficult due to inability to delete dependent resources.
depends on: https://github.com/RedHatQE/wrapanapi/pull/453

change -all flag to remove whole group

---

Dockerfile.dev

Hello,
As a docker image size best practice, git depth was lowered to 1, so git history will not be downloaded to the image.
Currently, disk space difference is not dramatic (saves 8KB), but as we will have more branches / more commits, it can be substantial.
Thanks.

remove git history from image

---

Dockerfile.dev
Dockerfile.stable

Hello guys,
As cloudwash is accepting ENV variables for secrets, and also have a virtual environment configured in the container, it creates a challenge:
Environment variable that was created in session A, will not be available for session B (same container).
To overcome it, I added a .profile file that can be modified by the user in session A, and make the environment variable available for session B as well.
Let me know what you think.

added .profile file to keep environment variables

---

Dockerfile.dev

With the recent change from #24 , the development docker images should now install from setup as requirements file is removed.

Dockerfile.dev installs from setup.cfg instead of requirements

---

.github/workflows/new_release.yml

Auto PyPi release failing with PyCurl https://github.com/RedHatQE/cloudwash/runs/7061757863?check_suite_focus=true. This PR fixes that.

Fix PyPi failing with cloudwash setup

---

cloudwash/providers/azure.py
cloudwash/providers/ec2.py
cloudwash/providers/gce.py
cloudwash/utils.py
settings.yaml.template

Addresses #11 and logging improvements !
Improvements:
- Now to stop the VM it does not required to follow the `delete_vm` setting from `settings.yaml`. In short, VM with any prepended text should be good to stop.
- But the stop VM still follows the VM Running time settings.
- For skip, the VM neither follows running time nor prepended text settings.

Except VMs list from deleting and logging improvements

---

cloudwash/client.py
cloudwash/providers/ec2.py
settings.yaml.template

Adding support for deleting resources from multiple regions in AWS.
- The region for ec2 in settings.yaml will take the `list of regions` instead of a single region
Output:
```
$ swach -d ec2 --all
<<<<<<< Running the cleanup script in DRY RUN mode >>>>>>> 
The EC2 providers settings are initialized and validated !
Cleaning resources from the region: ap-south-1
=========== DRY SUMMARY ============
No resources are eligible for cleanup!
====================================
Cleaning resources from the region: eu-west-1
=========== DRY SUMMARY ============
No resources are eligible for cleanup!
====================================
Cleaning resources from the region: us-west-2
=========== DRY SUMMARY ============
No resources are eligible for cleanup!
====================================
``` …

Add support for deleting resources from multiple regions in AWS

---

settings.yaml.template

This PR will add comments on `AWS` credentials to make explicit the equivalences for `ACCESS_KEY` and `SECRET_KEY` on the settings file for EC2 provider

Added comments for aws credentials on settings template file

---

.github/workflows/new_release.yml

Currently the packaging is broken from PyPi release GHA due to its missing the tags while building and hence checking out the new pip release (e.g 0.3.1) provides the older one e.g 0.2.1
Lets hope this PR fixes that !

Fix packaging with tags

---

.github/dependabot.yml

Allows Dependabot App to automatically raise PRs for updating the cloudwash Python package and GitHub Action requirements.

Automatically Update Dependencies using Dependabot

---

cloudwash/providers/aws.py
cloudwash/providers/azure.py
cloudwash/providers/gce.py
conf/aws.yaml.template
conf/azure.yaml.template
conf/gce.yaml.template
settings.yaml.template

Found typo putting exception instead of exceptions breaking VM exception functionality for all cloud providers. cc @jyejare

Bugfix & remove redundant template parameters

---

conf/aws.yaml.template
conf/azure.yaml.template

Fixes #68 
Aligning settings Compute bases settings-files settings names with settings.yaml.template that fixes the issue of settings names mismatched in two different settings files.

Fixes #68 - Fix Typo in Compute based settings

---

.github/workflows/new_release.yml
.github/workflows/pull_request.yml
Dockerfile.dev

This PR updates cloudwash's Dockerfile to use Python 3.11. The `python-311` image is built the same way as the UBI images, so the difference between them is minimal.

Update Dockerfile and GitHub Actions to use Python 3.11

---

cloudwash/cli.py
cloudwash/providers/aws.py
cloudwash/providers/azure.py
cloudwash/utils.py
conf/aws.yaml.template
conf/azure.yaml.template
settings.yaml.template

Links HMS-2043
```
(cloudwash) ➜  cloudwash git:(support_image_removal) ✗ swach -d aws --all
<<<<<<< Running the cleanup script in DRY RUN mode >>>>>>>
The AWS providers settings are initialized and validated !
Resources from the region: us-east-1
=========== DRY SUMMARY ============
IMAGES:
Deletable: ['ami-0ba22849118c7101a', 'ami-03d1c1aee99de0c58']
====================================
(cloudwash) ➜  cloudwash git:(support_image_removal) ✗ swach -d azure --all
<<<<<<< Running the cleanup script in DRY RUN mode >>>>>>>
The AZURE providers settings are initialized and validated !
Resources from the region and resource group: eastus/redhat-deployed
=========== DRY SUMMARY ============
DISCs:
Deletable: ['composer-api-qwd_disk1_9556a6aca0324ac5adf7e4a700f1c09b']
NICs:
Deletable: …
```

Adding image cleanup for clouds

---

cloudwash/entities/base.py
cloudwash/entities/resources/aws.py
cloudwash/providers/aws.py

New changes to the Code Base! 
- A grandparent AbstractClass 'ResourceCleanup' for all resource types cleanup
- A Resource Type Abstract class that every resource provider has to inherit 
- This PR includes `VMsCleanup` abstract class 
- That abstract class to be inherited by individual resource provider Resource Type class. 
- E.g in this PR here AWS 'CleanVMs'
- The logging and dry data setting is now native to resource provider Resource Type class directly.

[Develop] Code Abstraction/Standardisation of Resource Types 

---

.pre-commit-config.yaml
cloudwash/providers/aws.py

Older flake8 hook fails on latest Python 3.12, updating it solves the issue
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
Traceback (most recent call last):
File "/Users/username/.cache/pre-commit/repo6a3dbdvc/py_env-python3.12/bin/flake8", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/username/.cache/pre-commit/repo6a3dbdvc/py_env-python3.12/lib/python3.12/site-packages/flake8/main/cli.py", line 22, in main
app.run(argv)
File "/Users/username/.cache/pre-commit/repo6a3dbdvc/py_env-python3.12/lib/python3.12/site-packages/flake8/main/application.py", line 363, in run
self._run(argv)
File "/Users/username/.cache/pre-commit/repo6a3dbdvc/py_env-python3.12/lib/python3.12/site-packages/flake8/main/application.py", …
```

Update pre-commit hooks

---

.pre-commit-config.yaml

- Gitleaks to catch the secrets being pushed to public repo

Adding gitleaks pre-commit hook to refrain from pushing secrets

---

cloudwash/entities/resources/discs.py

Resolves #129 
To resolve this issue, ensure that the settings configuration is correctly set up and includes the necessary attributes for the specified cloud provider. Review the configuration files and update them accordingly to include the required attributes for Azure resource cleanup.

[bug-fix] mismatch provider name in discs cleaup in `Developer` Branch

---

cloudwash/constants.py
cloudwash/entities/providers.py
cloudwash/entities/resources/base.py
cloudwash/entities/resources/discs.py
cloudwash/entities/resources/images.py
cloudwash/entities/resources/nics.py
cloudwash/entities/resources/pips.py
cloudwash/entities/resources/stacks.py
cloudwash/providers/aws.py
cloudwash/providers/azure.py

Moved Cleanup Implementation: Instead of implementing each cleanup method directly in the cleanup() function, I've abstracted the cleanup logic into separate classes. Each cleanup type (e.g., Pips, NICs, Images) now has its own class with a cleanup() method. This follows the principle of separation of concerns and improves code organization.

refactored with new design for resource images, stacks, nics, pips

---

cloudwash/cli.py
cloudwash/providers/aws.py
cloudwash/utils.py
settings.yaml.template

Main flow:
1. Fetching OCP resources using [RedHatQe/wrapnapi](https://github.com/RedHatQE/wrapanapi/blob/master/wrapanapi/systems/ec2.py#L1810)
- AWS Resource Explorer official docs:
- https://docs.aws.amazon.com/resource-explorer/latest/userguide/welcome.html
2. Filtering resources using the `kubernetes.io/cluster/*` tag regex
3. Resources without associated EC2 Instances considered as leftovers
- Filtered by the last time modified
4. Resources associated with EC2 Instances are filtered by their EC2 Instances time modified
5. **For simplicity- deletion process will be separated by a following PR**

 Add support for collecting deletable OCP leftovers from AWS

---

.pre-commit-config.yaml
cloudwash/constants.py
cloudwash/entities/providers.py
cloudwash/entities/resources/vms.py
cloudwash/providers/gce.py
settings.yaml.template

GCE cleanup is rebased with Develop branch code for the latest code refinement.
Depends on: https://github.com/RedHatQE/wrapanapi/pull/484

Develop: Rebase GCE cleanup

---

README.md
cloudwash/cli.py
cloudwash/client.py
cloudwash/constants.py
cloudwash/entities/providers.py
cloudwash/entities/resources/base.py
cloudwash/entities/resources/containers.py
cloudwash/providers/podman.py
cloudwash/utils.py
settings.yaml.template

This PR adds :
- Support is added for new podman provider and new container resource-type
Depends on:
- https://github.com/RedHatQE/wrapanapi/pull/490/ 
Logs:
```
<<<<<<< Running the cleanup script in DRY mode >>>>>>>
The PODMAN providers settings are initialized and validated !
=========== DRY SUMMARY ============
Containers:
Deletable: ['satci_028317bd', 'satci_05fcf328', 'satci_45d36389', 'satci_df218a23', 'satci_8495c229', 'satci_debadcd2', 'satci_279c111d', 'satci_13764a88', 'satci_6a90dcca', 'satci_cfdb58e3', 'satci_950b969d', 'satci_8e69c381', 'satci_3bac0d80', 'satci_6951fafd', 'satci_54597423', 'satci_a239bf73', 'satci_03422a78', 'satci_47a081d8', 'satci_553965b8', 'satci_dca3fb4e', 'satci_93506f68', 'satci_f17523aa', 'satci_44dfd3cf', 'satci_8ef89ca1', 'satci_fec8032a', …
```

Cloudwash supporting Containers cleanup

---

cloudwash/cli.py
cloudwash/client.py
cloudwash/constants.py
cloudwash/entities/providers.py
cloudwash/entities/resources/vms.py
cloudwash/providers/vmware.py
conf/vmware.yaml.template
settings.yaml.template

The PR includes:
- No new changes but the realignment of VMWare cleanup with develop branch

[Develop] VMWare cleanup alignment with Develop branch

---

cloudwash/cli.py
cloudwash/constants.py
cloudwash/entities/providers.py
cloudwash/entities/resources/base.py
cloudwash/entities/resources/ocps.py
cloudwash/providers/aws.py
cloudwash/utils.py
settings.yaml.template

Rebasing #134 with Develop branch.

Develop: Rebase for OCP resource cleanup on AWS

---

conf/aws.yaml.template

This file is out of date with the latest OCPs support.
This addition allows us to work with env vars and avoid using `settings.yaml` directly.

Add OCPs to conf/aws.yaml.template file

---

cloudwash/entities/resources/ocps.py
conf/aws.yaml.template
settings.yaml.template

Filter resources by ocp cluster prefix.
This is important when we want to free up resources in the context of a project or any associated key value.
Can be used with env var with specifying:
`export CLEANUP_AWS__CRITERIA__OCPS__OCP_PREFIX='["ocp-cluster-prefix"]'  `

Allow filter by cluster prefix

---

cloudwash/utils.py

Clears out extra `<br>` from generated report 
Example:
```
<table id="cloud_table">
<caption>Region: us-east-1</caption>
<tbody>
<tr>
<td>Deletable Ocps</td><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<td>my-ocp-leftovers<br></td>
</tr>
</tbody>
</table>
```

Clean up line breaks in HTML report
